#!/bin/sh
set -eu

# RUN
# Runs the MELA DEAP workflow

PROCS=${PROCS:-3}

THIS=$( cd $( dirname $0 ); /bin/pwd )
export T_PROJECT_ROOT=$( cd $THIS/.. ; /bin/pwd )
EQP=$T_PROJECT_ROOT/ext/EQ-Py

export PYTHONPATH=$T_PROJECT_ROOT/python:$EQP
export TURBINE_RESIDENT_WORK_WORKERS=1 # Number of workers of this type

swift-t -n $PROCS -p -I $EQP -r $EQP $T_PROJECT_ROOT/swift/workflow.swift $*
